
apiVersion: security.istio.io/v1beta1

kind: AuthorizationPolicy

metadata:

  name: allow-calculator-namespace

  namespace: {{ .Values.namespace }}

spec:

  action: ALLOW

  rules:

  - from:

    - source:

        namespaces: ["{{ .Values.namespace }}", "istio-system"]

