# Consolidated DestinationRule for add-service with versions
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: add-service
  namespace: calculator
spec:
  host: add-service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 2
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
      minHealthPercent: 50
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
# Consolidated DestinationRule for calculator-api with rate limiting
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: calculator-api
  namespace: calculator
spec:
  host: calculator-api
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 10
        http2MaxRequests: 100
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 3m
      maxEjectionPercent: 100
---
# DestinationRule for subtract-service
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: subtract-service
  namespace: calculator
spec:
  host: subtract-service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    loadBalancer:
      simple: ROUND_ROBIN
---
# DestinationRule for multiply-service
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: multiply-service
  namespace: calculator
spec:
  host: multiply-service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    loadBalancer:
      simple: ROUND_ROBIN
