apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: multiply-service-timeout
  namespace: calculator
spec:
  hosts:
  - multiply-service
  http:
  - route:
    - destination:
        host: multiply-service
    timeout: 3s  # Fail if service takes >3s
    retries:
      attempts: 2
      perTryTimeout: 1s
      retryOn: 5xx,reset,connect-failure,refused-stream
