# Allow all traffic within the calculator namespace
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-calculator-namespace
  namespace: calculator
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["calculator", "istio-system"]
---
# Specifically allow calculator-api to call backend services
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-backend-services
  namespace: calculator
spec:
  selector:
    matchLabels:
      app: add-service
  action: ALLOW
  rules:
  - {}  # Allow all
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-subtract-service
  namespace: calculator
spec:
  selector:
    matchLabels:
      app: subtract-service
  action: ALLOW
  rules:
  - {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-multiply-service
  namespace: calculator
spec:
  selector:
    matchLabels:
      app: multiply-service
  action: ALLOW
  rules:
  - {}
